<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ACTION_CBM</name>
   <tag></tag>
   <elementGuidId>9f34a931-7a34-40fc-8f2b-c615147e867c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CBM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CBM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>623eafe1-1fc9-40c7-b524-f705efda1306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4573b8a1-cca1-4878-85ec-7a3cc25c71d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-input input-text</value>
      <webElementGuid>b5ab9ac9-0af6-4e1a-bdcc-10de66df3641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CBM</value>
      <webElementGuid>14703a29-44fc-4f4f-815e-c7767cd41e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CBM</value>
      <webElementGuid>ad508128-89b7-4ff4-b5a8-ff0fe1a9baac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CBM&quot;)</value>
      <webElementGuid>bdb38f3d-a89c-4674-9d9e-10187ce5e95f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CBM']</value>
      <webElementGuid>5d120262-f7db-4ca6-bd23-f7f829bb02a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my-form']/table/tbody/tr/td/div/input</value>
      <webElementGuid>280915e9-b209-4b73-af9f-a87d934d4582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>4e115c8f-c271-4d78-a64d-9a027a2864ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CBM' and @name = 'CBM']</value>
      <webElementGuid>7034ea7f-014f-4ac8-b3b5-34338e61752a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
