<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_Username</name>
   <tag></tag>
   <elementGuidId>3dd0b031-eb0a-4791-a725-beee82aaccd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signInName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ff994af-dddd-4162-a869-8f6d2ce5435b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6202abfe-4997-4c67-bc04-2fdc3119fa06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInName</value>
      <webElementGuid>53b35148-1dfc-4d5d-aba1-b66e94266bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>94555c03-0f92-4c43-a7b1-39a44b6bac6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please enter valid username</value>
      <webElementGuid>1f872c99-1ef6-4b79-8307-619666d2b056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>e5759e5a-8bca-4c50-8340-f5db3c04b98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>5a46a036-2020-4faf-b29f-641373116659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInName&quot;)</value>
      <webElementGuid>a43ce9c7-540e-4cde-a8d6-293db33459d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signInName']</value>
      <webElementGuid>e739b7f6-72f8-40a0-bde1-e17aedc44408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='localAccountForm']/div[3]/div/input</value>
      <webElementGuid>938fe95a-ff05-43c9-bf99-27f23ed5d5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>724d428b-b4c9-402b-b251-8ef751aea7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'signInName' and @name = 'Username' and @title = 'Please enter valid username' and @placeholder = 'Username']</value>
      <webElementGuid>dab3fb7b-f0a6-4c1e-8350-67d1c44a6c7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
