<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(708 O, , Keefe Stravenue, Clet_a1b22d</name>
   <tag></tag>
   <elementGuidId>21a113cb-7b5d-4885-979a-b5eb051b2f44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmedQty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmedQty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>268fe7aa-9584-499e-84b5-c67831ceba95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9076f51f-4074-46d7-9e52-c908f94c2ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-input input-text input-qty</value>
      <webElementGuid>315545d1-2a60-4b79-b4aa-6d23a3daa54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmedQty</value>
      <webElementGuid>6a534b82-f41c-4966-86ac-f490f9277a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmedQty</value>
      <webElementGuid>4a277647-a680-470b-ae93-9d46be929bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmedQty&quot;)</value>
      <webElementGuid>037a8649-100a-4eed-b53b-575c2e2da3d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmedQty']</value>
      <webElementGuid>ab1c7091-0f67-4a7e-a03f-4597365b6685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my-form']/table/tbody/tr[2]/td[6]/div/input</value>
      <webElementGuid>95452f25-86f9-4d58-9186-b76c56684635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/input</value>
      <webElementGuid>2fc09a7e-dbb8-4094-9a63-70d9b6aad165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'confirmedQty' and @name = 'confirmedQty']</value>
      <webElementGuid>23c61ee1-28b2-4cd2-97da-f603713828ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
