<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(708 O, , Keefe Stravenue, Clet_affbe3</name>
   <tag></tag>
   <elementGuidId>8f9e64c3-9733-45d7-a675-2e817a1f0a0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;confirmedGoodsdate_0_0&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='confirmedGoodsdate_0_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d23f4da-cd8c-4fd3-8e87-16f2163a8461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text with-border date-input input-date-cursor</value>
      <webElementGuid>cd67f0f4-fd82-4f64-a2d1-3bdfe854239a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb87f1a0-38dd-442b-ad6b-08dfae8a4bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmedGoodsdate_0_0</value>
      <webElementGuid>fb0ff490-4f17-4e2f-ae7b-ce86bd749287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>0d886dba-9d44-43af-bdbe-f89ee8eafcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goodsReadyDateDiv&quot;)/div[@class=&quot;react-datepicker-wrapper&quot;]/div[@class=&quot;react-datepicker__input-container&quot;]/div[@class=&quot;modal-input-field-holder date-input-holder&quot;]/input[@class=&quot;modal-input input-text with-border date-input input-date-cursor&quot;]</value>
      <webElementGuid>8abd0619-8e3d-4f9c-b7f8-a77e94e7c223</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='confirmedGoodsdate_0_0']</value>
      <webElementGuid>c34959ce-16fe-4acc-bf81-188bdb2244c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='goodsReadyDateDiv']/div/div/div/input</value>
      <webElementGuid>b3a247f6-d4f5-4b3d-b50e-a2d7bdd8fc68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/div/div/div/div/input</value>
      <webElementGuid>d13a5f58-34ec-4d9f-a0e0-3127b8d0051a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'confirmedGoodsdate_0_0' and @placeholder = 'dd-mm-yyyy']</value>
      <webElementGuid>fb5bf2cb-dd14-4259-bd7e-be9bc9ab11da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
