<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__totalCoast</name>
   <tag></tag>
   <elementGuidId>3e0d75a1-2de5-4d27-b2fa-dc719e93d788</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#totalCoast</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='totalCoast']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40d6ba24-8e12-4ecb-9baf-5cd74196cc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Total Cost</value>
      <webElementGuid>bfc93eb6-5fd8-4390-9ddc-00cac0ed8d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9137890d-7af3-4b1c-8c71-2811cb7a195a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>totalCoast</value>
      <webElementGuid>dd2ff1f2-5624-4ff6-816d-9a2aa2526938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>totalCoast</value>
      <webElementGuid>139a46e3-ea0d-4bad-bde5-7407f7ebdaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text</value>
      <webElementGuid>01e9f8f5-1c68-4214-af3c-96aa776dbac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;totalCoast&quot;)</value>
      <webElementGuid>88d05402-982d-47cf-8c7b-298a24c748b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='totalCoast']</value>
      <webElementGuid>f35a0f11-5949-4110-b4c4-27d40158a074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/div/div/div[2]/div/div[2]/div[3]/div/div/div/div/input</value>
      <webElementGuid>bdd0ed30-4860-4ec8-8187-59a0616e7ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>bb695ea9-2d91-4aec-9832-95cbe0db46f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Total Cost' and @type = 'text' and @id = 'totalCoast' and @name = 'totalCoast']</value>
      <webElementGuid>bcdf5850-477e-4cbf-af66-7937c78b839a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
