<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PO Number_poNumber</name>
   <tag></tag>
   <elementGuidId>bb82ddfb-0268-4adb-a2c4-dc99c076bddb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#poNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='poNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1afdeb5-4c4d-4996-a6f4-24a3d8fa2155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter PO Number</value>
      <webElementGuid>17e29694-88d3-4b7a-aaf9-fb7e0379c817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec19635f-1bf9-49c4-a6e3-1a3434d6ec06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text</value>
      <webElementGuid>6f401597-8ae2-432a-ac98-4af6f4cc7ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>poNumber</value>
      <webElementGuid>4c8c55de-410e-4376-9622-b841d614975c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>poNumber</value>
      <webElementGuid>918c11e2-85ac-4de5-9908-70f597fb6fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;poNumber&quot;)</value>
      <webElementGuid>58979c1f-e8fc-45f8-8c81-952cb179622d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='poNumber']</value>
      <webElementGuid>86291654-17b8-44e9-bb72-7e4e1dd51d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my-form']/div/div/input</value>
      <webElementGuid>0a98e7e5-3d40-4869-a8fd-de46a3be40d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>32acbe45-fe86-455a-8bd3-cb136cc92a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter PO Number' and @type = 'text' and @id = 'poNumber' and @name = 'poNumber']</value>
      <webElementGuid>9fa60ef0-1a9c-4340-8221-f95c2749ee56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
