<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__masterBillNumber</name>
   <tag></tag>
   <elementGuidId>03798188-85d4-49eb-8721-6e0b3547cf28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#masterBillNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='masterBillNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>620653bf-c425-4b3e-b149-d810247fc99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Master Bill No.</value>
      <webElementGuid>add94fb8-2cf0-43cc-86f3-4931e1b778c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>affacc01-f99f-45f6-8037-35039f86ed7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text</value>
      <webElementGuid>05c40879-c501-49be-ab4f-fb8b6c4c6a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>masterBillNumber</value>
      <webElementGuid>a21e1718-b6aa-46fc-aef9-53bbaac99ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>masterBillNumber</value>
      <webElementGuid>9f19a3c4-9057-4227-a7c9-fd6b4d8697fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c02f62a8-4e50-4395-96c1-1a209818bd55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;masterBillNumber&quot;)</value>
      <webElementGuid>2234c2eb-363f-404f-999e-dbdda733e1aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='masterBillNumber']</value>
      <webElementGuid>063d40e2-b732-407e-9d19-3522b110371f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name_div']/div/input</value>
      <webElementGuid>b3ac4108-86e4-4e0e-a0d6-0e002420d0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>763dad21-b132-49a7-b83b-58fd20a92861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Master Bill No.' and @type = 'text' and @id = 'masterBillNumber' and @name = 'masterBillNumber']</value>
      <webElementGuid>27430cfc-7494-46e0-b141-c590fb8ff0e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
