<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__soNumber</name>
   <tag></tag>
   <elementGuidId>461c9843-affb-4bee-b64c-2d6a0c682eeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#soNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='soNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9baed14d-55fe-4a17-afab-bf5e421317f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter SO Number</value>
      <webElementGuid>828b17eb-10a6-4103-b8c7-1196f53bd128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7171bb82-1b09-466d-bfb6-e13b0c5e9fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text</value>
      <webElementGuid>d4258483-ac2b-43e8-8184-4aeaaebf9556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>soNumber</value>
      <webElementGuid>9df8e71a-0ec9-4b46-8135-38360fa06645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>soNumber</value>
      <webElementGuid>b0828101-1a25-4275-8a50-8e783a6e2efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>fa5872b4-aef3-44db-be48-9e84ef344287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;soNumber&quot;)</value>
      <webElementGuid>111f7b66-b6a1-453a-b60e-91caa17d5ed1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='soNumber']</value>
      <webElementGuid>4311086f-c9f2-44f6-8ccf-cb0c1555fef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='name_div']/div/input)[2]</value>
      <webElementGuid>212ea8fd-64cf-48f4-ab41-cf04d3511635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>4796e24a-dfbd-4de0-94a3-efbf0a23d7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter SO Number' and @type = 'text' and @id = 'soNumber' and @name = 'soNumber']</value>
      <webElementGuid>eb89c7b0-fb11-4629-936c-120d0f0c764b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
