<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__houseBillNumber_10003</name>
   <tag></tag>
   <elementGuidId>3cbc0527-93d9-461d-abc1-d8c6ab7c00ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#houseBillNumber_10003</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='houseBillNumber_10003']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03dac282-0815-446f-8b72-1d8d18c0471e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter House Bill Number</value>
      <webElementGuid>96f877f8-a4b0-47e9-9aab-7d88bb2eb7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9dbbb1f0-b3a2-4cf8-89e3-2fd83a944e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>8f1fbd9d-9f7e-4508-8279-03c1185c09ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text</value>
      <webElementGuid>a3bcc258-fcff-4b73-b19f-694bdde7bcf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>houseBillNumber_10003</value>
      <webElementGuid>1e054cf6-0be6-4371-b43e-f58a823e87d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>houseBillNumber_10003</value>
      <webElementGuid>9267a227-94c0-4ec6-ae0d-78de9cf92427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;houseBillNumber_10003&quot;)</value>
      <webElementGuid>a258016b-8034-435b-b9f6-29106ef38d72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='houseBillNumber_10003']</value>
      <webElementGuid>3416c918-9f74-4e10-a5b6-230d9a8fcc0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my-form']/div[3]/div/input</value>
      <webElementGuid>2ac4ec35-bdcb-48e3-b6dc-386d1c236317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>8730206f-06ca-429b-b6e7-4b27261a2881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter House Bill Number' and @type = 'text' and @id = 'houseBillNumber_10003' and @name = 'houseBillNumber_10003']</value>
      <webElementGuid>44ab7201-fb17-45cf-aa41-eb22237e2954</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
