<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add Details</name>
   <tag></tag>
   <elementGuidId>f16efc56-8a83-4e0a-bfa5-663158e6f103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.booking-detail-wrapper > div.card.details-box.custom > div.card-head-holder.add-btn-holder > div.btn-holder > button.app-btn.app-btn-secondary.icon-button > span.button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div[2]/div/div/div[2]/div/div/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f58c7b0c-126e-433d-a746-9f6af01b3b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-text</value>
      <webElementGuid>ec5df481-9149-424c-8697-f1ab8f0a6c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Details</value>
      <webElementGuid>c35a4727-31e0-4b8a-9443-52e218677232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-wrapper container&quot;]/div[@class=&quot;content-section main-wrapper bo-additional-detail&quot;]/div[@class=&quot;main-wrapper&quot;]/div[@class=&quot;booking-additional-detail-wrapper&quot;]/div[@class=&quot;booking-detail-wrapper&quot;]/div[@class=&quot;card details-box custom&quot;]/div[@class=&quot;card-head-holder add-btn-holder&quot;]/div[@class=&quot;btn-holder&quot;]/button[@class=&quot;app-btn app-btn-secondary icon-button&quot;]/span[@class=&quot;button-text&quot;]</value>
      <webElementGuid>fee4ddba-4a1c-43e0-9ff9-485c9092c61b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/div/div/div[2]/div/div/div[2]/button/span</value>
      <webElementGuid>fb70ee86-94a1-4f35-af96-e5ccaa024ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Booking Details'])[1]/following::span[1]</value>
      <webElementGuid>b65a73e0-c3b3-4ebb-b13b-fa1ebaa9fcef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shippingline contract3-v2.2'])[1]/following::span[1]</value>
      <webElementGuid>c9904497-baae-4e3a-9e9c-aea624f051de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::span[1]</value>
      <webElementGuid>2fc4ca1b-c999-476e-8ab9-2882a1371f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button/span</value>
      <webElementGuid>0657da97-e3ec-4aaf-96d7-b036d3abb9ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add Details' or . = 'Add Details')]</value>
      <webElementGuid>52da7ca1-8873-4487-960d-2ca65ad21618</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
