<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_16</name>
   <tag></tag>
   <elementGuidId>9cb8614f-7f96-46ab-82c5-fab321f9d01a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.react-datepicker__day.react-datepicker__day--016</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='date-portal']/div/div/div[2]/div/div/div[2]/div[2]/div[3]/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>df834df9-e8cf-4239-b136-8c2fdcf99d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-datepicker__day react-datepicker__day--016</value>
      <webElementGuid>bf108231-f508-49c7-b183-742864dab2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>96277088-0c90-4b05-9568-d0d459f2b2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Choose Thursday, February 16th, 2023</value>
      <webElementGuid>d7e968ac-964a-4646-aafb-481b7315d22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8eec745c-c3c6-4fcb-b467-6612907b1413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2bf68dc8-de48-4722-8e73-9b3c833595c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9a002718-984f-4af7-8f9a-01d864ba9e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>bb5549b6-e88e-401f-b560-65be324fc4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date-portal&quot;)/div[1]/div[@class=&quot;react-datepicker__tab-loop&quot;]/div[@class=&quot;react-datepicker-popper&quot;]/div[1]/div[@class=&quot;react-datepicker&quot;]/div[@class=&quot;react-datepicker__month-container&quot;]/div[@class=&quot;react-datepicker__month&quot;]/div[@class=&quot;react-datepicker__week&quot;]/div[@class=&quot;react-datepicker__day react-datepicker__day--016&quot;]</value>
      <webElementGuid>e60e35bb-58bc-482d-96e3-99d9d79890d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='date-portal']/div/div/div[2]/div/div/div[2]/div[2]/div[3]/div[5]</value>
      <webElementGuid>ec0b7f0e-48b4-4d88-ac04-77e64b886991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::div[23]</value>
      <webElementGuid>541ab107-1bdd-4a86-a6ba-b57c00f21401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::div[24]</value>
      <webElementGuid>1233c6d1-46ec-4b72-8abb-e619f9c09a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='16']/parent::*</value>
      <webElementGuid>b88f4aa8-3177-4914-b753-d0b99f94c4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[5]</value>
      <webElementGuid>afcf68aa-a99b-495b-8f22-5a6f06dc3d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '16' or . = '16')]</value>
      <webElementGuid>b3ba3b0b-450c-4279-9465-29b6260fcb84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
