<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AED_unitCost</name>
   <tag></tag>
   <elementGuidId>ac8aea7f-120c-433d-b688-b0622f297433</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unitCost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unitCost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d11b6e8-13d0-4da0-b6f9-1faab60075c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter unit cost</value>
      <webElementGuid>b2d11557-f907-4e7d-8c96-45f917dce875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>90fa6dca-2a18-4d06-b8d8-cb8e74e73a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-input input-text input-qty</value>
      <webElementGuid>3fe4433b-8133-4574-89ab-8cfa9b359ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unitCost</value>
      <webElementGuid>0af77967-86d8-44ba-b2cc-50403a674155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unitCost</value>
      <webElementGuid>b8bc221e-1886-4c58-9629-7f9c2a06332b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>755adb2b-c2ac-40e5-af03-37345cda1768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>40b2dffd-25ee-4fdc-8dc0-ec08e1bcad0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unitCost&quot;)</value>
      <webElementGuid>1fba1429-e7b8-4cb5-af0a-58f0ff83afee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unitCost']</value>
      <webElementGuid>6fe1b2f3-2b6e-4f27-880d-f595af73c955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='unitCost_div']/input</value>
      <webElementGuid>6558c3ee-67e7-43d5-9fa6-2f8d725f47a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/input</value>
      <webElementGuid>87a8217f-fc32-4559-a46f-d14c3c815c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter unit cost' and @type = 'number' and @id = 'unitCost' and @name = 'unitCost']</value>
      <webElementGuid>36ce933f-e0d5-44ed-b84d-27c59f474e66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
