<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ship Bottom(USSBQ)</name>
   <tag></tag>
   <elementGuidId>6501e8ac-533a-49df-b90f-f0caf03290ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-5-option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-5-option-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ce73b3b-f6fb-46c4-9b1d-2720914a6393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-a4wmji-option</value>
      <webElementGuid>44a7f239-ebe4-40fc-92ee-9d5c65b6247e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6c0d160e-a39a-4cf4-9946-dcd07d7ecb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-5-option-1</value>
      <webElementGuid>83f3db94-e6eb-4046-a42f-67f3bcfa6ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ca9d6716-1488-4ed8-83c8-509e0a7affaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ship Bottom(USSBQ)</value>
      <webElementGuid>ee06e613-d626-4e3f-9402-dbe7100a6733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-5-option-1&quot;)</value>
      <webElementGuid>c62d6b55-bccf-4e40-962b-539d89546bf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-5-option-1']</value>
      <webElementGuid>3d9debdf-faa2-49cf-9597-4c8d3a8e5d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-5-listbox']/div/div[2]</value>
      <webElementGuid>245361b3-4f12-44ca-ba7a-6d5aa4bcd667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saint Clair Shores(USCS4)'])[1]/following::div[1]</value>
      <webElementGuid>7460c950-bfaf-43aa-b67e-a10c3aad2879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/following::div[9]</value>
      <webElementGuid>2cd4f9f5-033f-4647-bdaf-d744599d446a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi destination'])[1]/preceding::div[2]</value>
      <webElementGuid>643f3476-2a9c-486a-9125-2458c312d5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ship Bottom(USSBQ)']/parent::*</value>
      <webElementGuid>c2e7086b-ffe6-4ed3-9c21-105e0cf364ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div[2]</value>
      <webElementGuid>85f71fff-5653-4e1b-921c-4906ac66a554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-5-option-1' and (text() = 'Ship Bottom(USSBQ)' or . = 'Ship Bottom(USSBQ)')]</value>
      <webElementGuid>b053bcac-dfd9-46ba-be16-b818eaa17e95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
