<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AED_unitCost</name>
   <tag></tag>
   <elementGuidId>0a491e54-c92c-4547-bd61-909196a0073e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unitCost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unitCost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd55cb26-9422-45b0-845a-d894104a6846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter unit cost</value>
      <webElementGuid>bb73dbd6-04d3-40a8-97b0-be3d1b2c20ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0d987279-833d-4959-8a73-bb314c0f435f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-input input-text input-qty</value>
      <webElementGuid>5d619d93-f3a8-431b-bbcb-1c16a94b1f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unitCost</value>
      <webElementGuid>288d323b-4e24-4fac-8ea1-a7867523e620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unitCost</value>
      <webElementGuid>810e76ee-628a-4759-936a-b2e251ba281b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>084be946-1c17-4314-90a0-e2df9e5c42f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>4b4f4bd9-6ebe-43b9-b37f-e3e74d518f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unitCost&quot;)</value>
      <webElementGuid>235a2d00-1382-48f3-82fd-2f1cf4efa568</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unitCost']</value>
      <webElementGuid>2a6840cb-ed02-443a-805d-d674bc9559e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='unitCost_div']/input</value>
      <webElementGuid>f39a6686-e9a9-4549-a28e-7c2de07594d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/input</value>
      <webElementGuid>8db1cf84-5f4c-4d16-aa97-fa4d2c896e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter unit cost' and @type = 'number' and @id = 'unitCost' and @name = 'unitCost']</value>
      <webElementGuid>4ed3e803-2067-48b0-aa82-606345765463</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
