<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(9699 O, , Conner Circle, Water_0429e9</name>
   <tag></tag>
   <elementGuidId>0be3f5ea-cd6f-4f91-b080-5e35badcd3bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;confirmedGoodsdate_0_0&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='confirmedGoodsdate_0_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2ea77dc-bca5-42eb-b5e6-8c03a9b396c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text with-border date-input input-date-cursor</value>
      <webElementGuid>468595ff-3d2f-458a-951f-2e46fc0fa73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb4f5d3a-66ae-4d49-94d7-4405bd60ce4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmedGoodsdate_0_0</value>
      <webElementGuid>0c05c802-ae2c-40bb-afb7-301da284e6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>4500ceed-0432-4d4e-b040-4090932c0d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goodsReadyDateDiv&quot;)/div[@class=&quot;react-datepicker-wrapper&quot;]/div[@class=&quot;react-datepicker__input-container&quot;]/div[@class=&quot;modal-input-field-holder date-input-holder&quot;]/input[@class=&quot;modal-input input-text with-border date-input input-date-cursor&quot;]</value>
      <webElementGuid>33942fc7-74b1-4cdc-840f-a2ce3ff96dd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='confirmedGoodsdate_0_0']</value>
      <webElementGuid>245c6fab-d5fc-4197-932b-eb5ed4c0180e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='goodsReadyDateDiv']/div/div/div/input</value>
      <webElementGuid>7ddc83b5-7677-4b22-8630-8ce43164b7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/div/div/div/div/input</value>
      <webElementGuid>0fef59a4-add6-4a13-a79c-c2efd6b0eec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'confirmedGoodsdate_0_0' and @placeholder = 'dd-mm-yyyy']</value>
      <webElementGuid>606eef65-39b1-41f0-a377-40ce074dd107</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
