<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__costSellAmount</name>
   <tag></tag>
   <elementGuidId>baf30571-e003-4f7d-9f91-61b51ed16603</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#costSellAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='costSellAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a98a3dd2-8938-4cfb-a61c-00308f7ab3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Total Cost</value>
      <webElementGuid>a986ade6-1f28-4836-a7ff-b9a7affcdec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b6842b56-8047-4306-be36-4e69528083c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>c90ea590-7489-4916-8f4c-f234ca7f37c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>73f62290-8445-4437-a641-8a0b2b7f2de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>costSellAmount</value>
      <webElementGuid>075a92ea-37a3-45cc-9958-284664f76615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>costSellAmount</value>
      <webElementGuid>f2e1a668-9e0c-4da2-bd90-9133d085265b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text</value>
      <webElementGuid>1e0a2bf4-34fa-49cc-ae91-9305de65e3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;costSellAmount&quot;)</value>
      <webElementGuid>58a596c4-2c88-4aa1-83fc-229b784dde1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='costSellAmount']</value>
      <webElementGuid>bef87f29-7d59-46e7-9071-a3047f5c9e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my-form']/div/div/div/div/input</value>
      <webElementGuid>2ffe0291-7249-4721-a95d-34c847458ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/input</value>
      <webElementGuid>f5b535fa-c523-4bd5-bea5-e99efb646dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Total Cost' and @type = 'number' and @id = 'costSellAmount' and @name = 'costSellAmount']</value>
      <webElementGuid>f6e533f8-308d-4c49-a156-a02ef28b19d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
