<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Shipping Window_endShipWindowDate</name>
   <tag></tag>
   <elementGuidId>3f92aac8-42b0-4fc2-8bc2-4998ad968d36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;endShipWindowDate&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='endShipWindowDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>962d48d1-84b4-43ab-8e8d-fd36479842b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text with-border date-input input-date-cursor</value>
      <webElementGuid>16bef8b6-4156-4070-8973-76c97b2b3999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1e13ef71-f48e-4dc8-b640-de75c0e183ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>cbe6e604-bc36-419f-bec1-a79a846c2166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>endShipWindowDate</value>
      <webElementGuid>99a3fe19-5b92-45a5-bd6e-044f6ff37f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-form&quot;)/div[@class=&quot;modal-input-holder&quot;]/div[@class=&quot;modal-input-layout-item calendar&quot;]/div[@class=&quot;react-datepicker-wrapper&quot;]/div[@class=&quot;react-datepicker__input-container&quot;]/div[@class=&quot;modal-input-field-holder date-input-holder&quot;]/input[@class=&quot;modal-input input-text with-border date-input input-date-cursor&quot;]</value>
      <webElementGuid>99c3292b-8588-4d0a-b789-4384e9ccca2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='endShipWindowDate']</value>
      <webElementGuid>a4cbe5ba-bcb5-46c7-8f39-5671ade908a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my-form']/div[3]/div/div/div/div/input</value>
      <webElementGuid>f52c2006-ebc2-4ca3-94af-1fb5d6854f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>c3f97d72-cc27-46a7-975c-8b290c4cc42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'dd-mm-yyyy' and @name = 'endShipWindowDate']</value>
      <webElementGuid>2080662b-2623-4f31-8a58-a837d150a6ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
