<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AED_unitCost</name>
   <tag></tag>
   <elementGuidId>ea527e33-2f33-41c8-9393-ae2e6b6a5b32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unitCost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unitCost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fe4b5d3-3f61-47e7-9a89-fb43fd0d1bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter unit cost</value>
      <webElementGuid>e776bab5-2943-47fa-988b-931fc8431612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>50c53cf3-5f49-4e0b-beb4-0f973c019966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-input input-text input-qty</value>
      <webElementGuid>cbc63d9d-b922-458e-9088-3ddad8126277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unitCost</value>
      <webElementGuid>4577b97e-532d-4cbe-a69d-5b8b00afa532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unitCost</value>
      <webElementGuid>95fe4041-5599-4927-9ed5-83a00d68a0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7d5042ac-219c-43ee-8a49-ced8bfb8fcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>d0f39f8b-1a2f-4ed5-b188-bbb30c02beb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unitCost&quot;)</value>
      <webElementGuid>d66dee8f-30d1-43ef-9687-0cb5ce8a271e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unitCost']</value>
      <webElementGuid>494b3a86-18f6-48a2-96c4-5790440d97ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='unitCost_div']/input</value>
      <webElementGuid>e36025e1-e5ee-44ae-a02c-84b8a7595042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/input</value>
      <webElementGuid>1cf3f689-959b-4b5d-a9c3-b4df2f352d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter unit cost' and @type = 'number' and @id = 'unitCost' and @name = 'unitCost']</value>
      <webElementGuid>878ebece-1c48-4af6-821a-2e52092ebb6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
