<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_Username</name>
   <tag></tag>
   <elementGuidId>9774c079-3395-4de0-b343-1ddb92fd7df5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signInName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc2ab3d1-2036-4589-9b59-22e60fbef29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ba7f5e7-f0dc-4266-ab3d-f7e30778f015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInName</value>
      <webElementGuid>2bc9b612-92c5-4243-8d31-168f83fb1e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>b3a96745-babe-4e24-963d-327b0216c00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please enter valid username</value>
      <webElementGuid>c9b04566-f692-4ff3-961b-6b6c417069e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>01b3e408-d352-4c7d-a8b7-cc499a667082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>e39fd535-101b-40ff-96ca-c60f52fcf6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInName&quot;)</value>
      <webElementGuid>ebcd4ae1-cbf2-453b-8eea-f70f2bde0280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signInName']</value>
      <webElementGuid>7c455b88-516b-44b9-a47c-f9fdea54080f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='localAccountForm']/div[3]/div/input</value>
      <webElementGuid>298c9276-c94c-4adc-8ac3-f8e2f3cb1985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1dd01ec7-c1f3-49db-b0ff-42ae2fa4e515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'signInName' and @name = 'Username' and @title = 'Please enter valid username' and @placeholder = 'Username']</value>
      <webElementGuid>d94d9fcc-24a0-4137-9041-e5e31dffd2e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
