<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__bookingQuoteNumber</name>
   <tag></tag>
   <elementGuidId>57e1c327-516b-429e-a435-cadf227881ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bookingQuoteNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bookingQuoteNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd395c9b-dcce-4ae6-9ea4-d7735493c04b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Booking Quote Number</value>
      <webElementGuid>058d1366-60f9-47f7-b51d-e8ca1869e18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f90820c2-6603-4f46-9fb4-6fc3a21a95df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text</value>
      <webElementGuid>a09c2b99-9df2-479d-8443-65aa57519fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bookingQuoteNumber</value>
      <webElementGuid>126d815e-b6a4-4ce9-b596-e4646d44a6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c3c52dcc-50f2-41d1-8cc7-cac5e9ff38a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3abc7c1a-39e8-4696-b31e-dcfc20b7a51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bookingQuoteNumber&quot;)</value>
      <webElementGuid>4d0fabc9-569a-4db7-877a-bcc9bffb74ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bookingQuoteNumber']</value>
      <webElementGuid>97dbab58-133f-4716-b96b-9ef6751d4053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/div/div/div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>7b01f706-7a5a-46f9-bc55-759c9ce76a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>9cf72b71-9205-4bdc-8e32-fbc1ed38d3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Booking Quote Number' and @type = 'text' and @id = 'bookingQuoteNumber']</value>
      <webElementGuid>2b52cc0d-9ee8-4036-9c6f-c37df49cb399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
