<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Melbourne(AUMEL)</name>
   <tag></tag>
   <elementGuidId>fee9ad0a-e1f0-4efc-9054-ebcf97c1c17a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-4-option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-4-option-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ccb4b1d1-71e6-4800-8bc8-e4876facf884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-a4wmji-option</value>
      <webElementGuid>7e012707-a59b-43bd-b927-408ede6d1670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>af2212e2-e9e4-44e1-b9c4-fc2aca26b88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-4-option-1</value>
      <webElementGuid>ccdea820-cb5d-4192-9c51-fdffa7108134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>425f8fa2-0bd7-4e9a-a704-57a388f1be1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Melbourne(AUMEL)</value>
      <webElementGuid>a1fe7975-53d8-41b4-8a69-c4cd02d2f97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-4-option-1&quot;)</value>
      <webElementGuid>0597880f-8d9c-4bb3-8ab3-724f9f7c1977</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-4-option-1']</value>
      <webElementGuid>3ca69cca-e327-45df-93e0-c5fefba7c78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-4-listbox']/div/div[2]</value>
      <webElementGuid>1a580362-3666-4630-b9d0-f8ef1ccfa459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Essendon Apt/Melbourne(AUMEB)'])[1]/following::div[1]</value>
      <webElementGuid>b7415d72-e457-4401-ac67-3eacc8f63c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::div[9]</value>
      <webElementGuid>5fdd8fd8-da51-4273-83e5-8498fb20bcae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Melbourne(USMLB)'])[1]/preceding::div[1]</value>
      <webElementGuid>59b56c1b-6d67-4fca-80b8-8efa6684b939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Melbourne City Heliport(AUKAH)'])[1]/preceding::div[2]</value>
      <webElementGuid>5066aea6-e912-4342-ab0a-b866f9d6e03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Melbourne(AUMEL)']/parent::*</value>
      <webElementGuid>a0ded722-0041-458b-9841-9da2b19a1d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div/div[2]/div/div[2]</value>
      <webElementGuid>614b3489-7cb0-4fbb-8b82-b7373deac323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-4-option-1' and (text() = 'Melbourne(AUMEL)' or . = 'Melbourne(AUMEL)')]</value>
      <webElementGuid>9076ffaf-8053-41bf-b9b4-50d81852e861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
