<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AED_unitCost</name>
   <tag></tag>
   <elementGuidId>ccdac0a5-b666-4035-b4b8-6b167104583a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unitCost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unitCost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38f1446c-d39f-4a48-9948-4cb35a5b4bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter unit cost</value>
      <webElementGuid>0e4fa135-2f4b-47e1-b020-4d039e287100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>3651950d-aeeb-43a8-8374-8b9144cd9a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-input input-text input-qty</value>
      <webElementGuid>e9eb6bd7-94ef-406c-8ec3-943018685cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unitCost</value>
      <webElementGuid>4d634c64-ea6e-4e82-86de-3b7fe550b101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unitCost</value>
      <webElementGuid>ca847cc1-4ed4-40e4-9351-caae1098fa6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>791acc9d-373d-457d-a3ff-c3494a5eed1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>c4459e01-3cff-4bd2-938f-5e62b22045b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unitCost&quot;)</value>
      <webElementGuid>5fb9f145-f189-475d-b8bf-e3299e26e808</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unitCost']</value>
      <webElementGuid>7d3dfd77-a391-424b-96ed-a7bffe9e963a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='unitCost_div']/input</value>
      <webElementGuid>c9c786bf-ccdb-4b6f-94b8-08a56e247c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/input</value>
      <webElementGuid>67bebbe9-0de2-420d-96fc-218abe0d582f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter unit cost' and @type = 'number' and @id = 'unitCost' and @name = 'unitCost']</value>
      <webElementGuid>37ed182d-c3ff-4dfe-b847-88f99258f265</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
