<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Loose</name>
   <tag></tag>
   <elementGuidId>f3ccf5bc-32a1-4543-93ac-b88ed02b1d19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='basic-details']/div[3]/div/div/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>af21bc28-cc65-4df9-b373-60d52ede1a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item app-btn</value>
      <webElementGuid>2563596a-3def-4ec8-880f-30ccbf506aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loose</value>
      <webElementGuid>300cecb3-83ce-4112-9689-66dad11a9dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic-details&quot;)/div[@class=&quot;modal-input-holder&quot;]/div[@class=&quot;modal-input-field-holder grey-option-box modal-input-layout-item&quot;]/div[@class=&quot;dropdown-wrap menu-down modal-dropdown dropdown-open&quot;]/div[@class=&quot;dropdown-wrap commercial-services-dropdown-wrap outside-menu menu-down dropdown-open modal-dropdown&quot;]/div[@class=&quot;dropdown-menu&quot;]/a[@class=&quot;menu-item app-btn&quot;]</value>
      <webElementGuid>a5fb8fa8-f1a2-48b2-9b65-6d1e7a5523b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic-details']/div[3]/div/div/div/div/a[2]</value>
      <webElementGuid>85f5d4b8-1361-4864-85d4-e730b4841ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Loose')]</value>
      <webElementGuid>f32b6dd2-54b5-4018-ae22-2c2f1ae196e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double Pallet'])[1]/following::a[1]</value>
      <webElementGuid>abf84e15-e3c0-4267-97b2-09dbfd304a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Packing'])[1]/following::a[2]</value>
      <webElementGuid>89826dcb-afd4-4de8-968a-f3a812208e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single Pallet'])[1]/preceding::a[1]</value>
      <webElementGuid>74bd218f-8a37-4497-a2c9-60899dd87fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Loose']/parent::*</value>
      <webElementGuid>4a251cf5-0bfc-4efa-ae3d-514c83d02d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/a[2]</value>
      <webElementGuid>69077f26-e5d3-470d-aedd-ad6010075dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Loose' or . = 'Loose')]</value>
      <webElementGuid>5eb26510-5e67-4e2d-8eb1-c684d7b4dca2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
