<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>e5086f2d-831e-41b9-b211-573d36f5e47f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.app-btn.app-btn-primary.modal-btn.form-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>91d6be97-9ff5-4d74-bc4c-47161d5b7db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-btn app-btn-primary modal-btn form-btn</value>
      <webElementGuid>827fc0ca-f46d-4579-9ef8-93c040f911cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>4ea3a8d5-d90d-4d17-90de-2ad2a10307c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>my-form</value>
      <webElementGuid>8771a821-919c-439a-9c7b-8b490c88d4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7dd1932b-142f-46c8-83d6-1a142354ed16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>411ac5ba-f3d2-4370-ac17-0d177a7795db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-form&quot;)/div[@class=&quot;form-submit-btn&quot;]/button[@class=&quot;app-btn app-btn-primary modal-btn form-btn&quot;]</value>
      <webElementGuid>3c9792ee-5cca-4937-8f57-1d5a901860a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>eb771075-0cbf-46d1-96f7-3bc8bc547848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my-form']/div[4]/button</value>
      <webElementGuid>6903e8be-e36d-41de-abeb-c36f5a7683c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Name'])[1]/following::button[1]</value>
      <webElementGuid>80d6811e-3692-4f08-b390-dc58c0f09ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YONGKANG JIGHONG TOOLS'])[1]/following::button[1]</value>
      <webElementGuid>ce74612d-5221-421e-83cd-71caec1d2a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>207dab9b-9a9c-4a8e-ac95-cc9c79c46fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Submit' and @form = 'my-form' and @type = 'submit' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>1893516d-b998-4191-8ed8-9f5b07a3260b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
