<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select Packingdropdown</name>
   <tag></tag>
   <elementGuidId>dcf47f4a-5da2-4f55-ab4a-5c5422597a4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.menu-btn.app-btn.modal-input.select-modal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2bfad299-c322-40af-8bf4-fb50b23a6e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>34091cff-d134-49e4-b53f-6461103d0033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-btn app-btn modal-input select-modal</value>
      <webElementGuid>48af80ea-6c55-498c-891e-6913061a0ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Packingdropdown</value>
      <webElementGuid>ef373385-0e75-462f-b4f1-760674499004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic-details&quot;)/div[@class=&quot;modal-input-holder&quot;]/div[@class=&quot;modal-input-field-holder grey-option-box modal-input-layout-item&quot;]/div[@class=&quot;dropdown-wrap menu-down modal-dropdown&quot;]/button[@class=&quot;menu-btn app-btn modal-input select-modal&quot;]</value>
      <webElementGuid>c91f65a8-605a-49d7-97fc-d134f053be77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>28dc086a-f54a-4983-b7a7-a3fa26e70ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic-details']/div[3]/div/div/button</value>
      <webElementGuid>74fb64b8-65b7-471b-8c5d-5cb69fa315ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::button[1]</value>
      <webElementGuid>32aa51b7-e803-4d81-af17-24b17282b529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double Pallet'])[1]/preceding::button[1]</value>
      <webElementGuid>31e328e2-5654-4207-bf66-a70f5d24e430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>3e0ecc19-9ece-47ad-b62d-664bce8f7b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Select Packingdropdown' or . = 'Select Packingdropdown')]</value>
      <webElementGuid>c5c483f3-e2a5-4b72-b1f2-1bde2a23dacb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
