<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cost Insurance  freight</name>
   <tag></tag>
   <elementGuidId>c7a78a09-f90a-48f5-8f1a-349cdd4e80f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-6-option-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-6-option-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a888386-6658-4a81-89f6-c1f26bc8ab2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-select__option react-select__option--is-focused css-7141g7-option</value>
      <webElementGuid>b8082b8c-8ce9-4f01-b983-ad8e76e3a63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b51245ee-4007-43de-a7e7-51e7eade2877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-6-option-3</value>
      <webElementGuid>31793d42-1f72-483b-b020-d9c0f8d67318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>451a1a30-7152-48e3-b9b3-db43f315890a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cost Insurance &amp; freight</value>
      <webElementGuid>d0e2d6e0-5cb4-4e0f-af74-1ac3945005cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-6-option-3&quot;)</value>
      <webElementGuid>45242b40-6aee-4fe6-8955-63043d7b8a48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-6-option-3']</value>
      <webElementGuid>4b6c3d98-2d10-43cf-a847-b318e2c6a0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-6-listbox']/div/div[4]</value>
      <webElementGuid>618cfdd5-12d3-4944-9cfc-28318abf2bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cost &amp; Freight'])[1]/following::div[1]</value>
      <webElementGuid>01d5f669-231d-44a5-8102-222f69cc3d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carriage Paid To'])[1]/following::div[2]</value>
      <webElementGuid>2ef3c5a8-0571-4754-adf5-8a1d51481d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivered At Terminal'])[1]/preceding::div[1]</value>
      <webElementGuid>e7f49bd5-14e8-4096-9ae6-f37504227f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivered Duty Paid'])[1]/preceding::div[2]</value>
      <webElementGuid>9f1c4989-403a-4518-80bc-8eea1a1d696e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cost Insurance &amp; freight']/parent::*</value>
      <webElementGuid>9841653e-f83f-42be-a59e-0cc3fdcb8fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div[4]</value>
      <webElementGuid>1a65342e-832c-4f0d-a405-17ce26ac487c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-6-option-3' and (text() = 'Cost Insurance &amp; freight' or . = 'Cost Insurance &amp; freight')]</value>
      <webElementGuid>4e9beb35-e4b4-4866-82bd-0c43ce3f185f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
