<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__origin_certificate</name>
   <tag></tag>
   <elementGuidId>7505d63f-5363-45b0-aa5e-1b0be1630f6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='ad_file'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a517dcb-f436-4799-8ca0-bc9d9d3ab0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>f2bb1a1a-f74e-4607-b354-790472b361e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ad_file</value>
      <webElementGuid>7596d5d9-ee86-49d2-9678-f12628f98d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ad_file</value>
      <webElementGuid>85e5596e-5d2d-452b-b730-ccfe0929eef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.doc,.docx,.mpp,.mppx,.pdf,.ppsx,.ppt,.pptx,.vsd,.vsdx,.xls,.xlsx</value>
      <webElementGuid>c4597f44-3bd2-464c-a3be-7f209efda69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>browse-input</value>
      <webElementGuid>3f45de1b-3d91-4ac9-885a-9c9eae0f692c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-wrapper container&quot;]/div[@class=&quot;content-section main-wrapper bo-additional-detail&quot;]/div[@class=&quot;main-wrapper&quot;]/div[@class=&quot;booking-attachment-wrapper&quot;]/div[@class=&quot;attachments-wrapper&quot;]/div[@class=&quot;card details-box custom&quot;]/div[@class=&quot;card-detail-col&quot;]/div[@class=&quot;attachment-items-holder&quot;]/div[@class=&quot;modal-input-holder upload-file-btn&quot;]/div[@class=&quot;modal-input-layout-item&quot;]/div[@class=&quot;browse-btn-wrapper&quot;]/input[@id=&quot;ad_file&quot;]</value>
      <webElementGuid>30623434-edd5-4904-b40e-3b9586153a1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='ad_file'])[1]</value>
      <webElementGuid>3845ba0b-8359-4787-a7a6-4ad04b3c9c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/div/div/div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>0286fb7f-2b5e-44e5-bd57-91fe8a7d00a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>b4a5d4bd-73b7-4caa-a90c-b8f5d18e9364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'ad_file' and @name = 'ad_file']</value>
      <webElementGuid>ad1816d1-c0a7-455a-be36-4107edc7573b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
