<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__commercial_invoice</name>
   <tag></tag>
   <elementGuidId>c004d9db-207c-49b3-8ffb-ac807894a9c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='ad_file'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a19ad9d1-b5f7-4cfc-a60c-e35215ee8bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>933d3494-b8c0-4723-97de-8c598575e6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ad_file</value>
      <webElementGuid>012ffd3e-0646-4ba5-ac93-9aeda7e65556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ad_file</value>
      <webElementGuid>e0364935-4f56-4881-a4c9-52b87c5fba44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.doc,.docx,.mpp,.mppx,.pdf,.ppsx,.ppt,.pptx,.vsd,.vsdx,.xls,.xlsx</value>
      <webElementGuid>c2b92795-9b4a-4c96-93d2-9045565db9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>browse-input</value>
      <webElementGuid>b8001d7a-ff73-48b2-9250-d2ad4ef15c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-wrapper container&quot;]/div[@class=&quot;content-section main-wrapper bo-additional-detail&quot;]/div[@class=&quot;main-wrapper&quot;]/div[@class=&quot;booking-attachment-wrapper&quot;]/div[@class=&quot;attachments-wrapper&quot;]/div[@class=&quot;card details-box custom&quot;]/div[@class=&quot;card-detail-col&quot;]/div[@class=&quot;attachment-items-holder&quot;]/div[@class=&quot;modal-input-holder upload-file-btn&quot;]/div[@class=&quot;modal-input-layout-item&quot;]/div[@class=&quot;browse-btn-wrapper&quot;]/input[@id=&quot;ad_file&quot;]</value>
      <webElementGuid>3814ff98-4c21-4169-a9a5-1ede3f84fca5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='ad_file'])[2]</value>
      <webElementGuid>bee030cb-9518-449d-a419-5d757d5c55b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/div/div/div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>fcae5579-40a3-4f66-915a-dd0b76c9dc91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>eada49be-a58f-4680-9fe4-7d18860b1235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'ad_file' and @name = 'ad_file']</value>
      <webElementGuid>a875cf6e-a83f-47de-91a4-03cebc717993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
