<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__vgm</name>
   <tag></tag>
   <elementGuidId>261bc317-6a4f-474c-9f01-50e15db092ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vgm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vgm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0dbca42e-cf18-4280-bd5b-efaefba6fb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter VGM</value>
      <webElementGuid>d82f8293-b5ac-4ecc-ad6a-666aa3589e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4fd69191-7b72-4277-bdb0-93cd1e17e43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text</value>
      <webElementGuid>c3b43749-e6df-47a2-a9d1-869e63bc5049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vgm</value>
      <webElementGuid>7be922f7-b05f-476b-97b1-a88c8193bdff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vgm</value>
      <webElementGuid>7039d146-077d-4f87-a6a1-669ca1187ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vgm&quot;)</value>
      <webElementGuid>30594725-9801-4571-9f84-4d5523448d64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vgm']</value>
      <webElementGuid>b6f21e50-f91b-4df4-b007-b172b9397c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic-details']/div[4]/div/input</value>
      <webElementGuid>e5897fbe-4306-4e54-9ad0-6602fb659730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>7d0e509e-9c07-4353-a030-c88e5726671e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter VGM' and @type = 'text' and @id = 'vgm' and @name = 'vgm']</value>
      <webElementGuid>4c685241-ce9a-45c3-8423-4e3d2263c60b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
