<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__quotationFile</name>
   <tag></tag>
   <elementGuidId>ad1d5c7e-0783-443f-8168-ebe21b05f93f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quotationFile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quotationFile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32a0c8ad-9ca8-4013-ab5e-da05c8b90678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>89ba87ab-2b54-4c4d-be8a-6e3b0bd65d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quotationFile</value>
      <webElementGuid>495b4e66-df66-4b69-af0a-5e55e0eb8a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quotationFile</value>
      <webElementGuid>3f2ed2d9-8bde-4501-87dd-7dcc2ac67d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.doc,.docx,.mpp,.mppx,.pdf,.ppsx,.ppt,.pptx,.vsd,.vsdx,.xls,.xlsx</value>
      <webElementGuid>a8460e8e-9d76-41fb-af1d-f3b63bf0ce3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>browse-input</value>
      <webElementGuid>3eed6bff-d78c-4da9-8e47-a9baf7e397b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quotationFile&quot;)</value>
      <webElementGuid>c921620f-16d7-440e-ba27-62781aab98b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quotationFile']</value>
      <webElementGuid>a51470b4-3100-492f-9284-a7de6f1bffb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my-form']/div[2]/div/div/input</value>
      <webElementGuid>6414796e-6648-4b28-8b48-df452e8f32a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>3e7ecb23-4753-4fed-8a45-9a357dca93c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'quotationFile' and @name = 'quotationFile']</value>
      <webElementGuid>0c5e2e58-fa20-45e7-9245-4e27209fe933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/div/div/div[2]/div/div[2]/div[4]/div/div/div/input</value>
      <webElementGuid>b78c13d8-a7f2-4bd9-aac4-acd8c40e57cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>185285f2-22d4-4d4c-bbf7-36db9b98e665</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
