<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Projected ETA into Warehouse_projectedEtaDate</name>
   <tag></tag>
   <elementGuidId>b1fd5357-335e-420c-90e5-f073b8d40485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;projectedEtaDate&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='projectedEtaDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5ba82e3-6059-4b2f-b7f2-739f5fcb488e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text with-border date-input input-date-cursor</value>
      <webElementGuid>72c8c848-3e40-42ca-bc72-303fba85596c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>517c84cf-6534-45b3-830d-92b82c86543d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>466ddf29-eb0a-4a7d-9d48-c10f761688ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>projectedEtaDate</value>
      <webElementGuid>59b14ece-4d18-4a6a-b099-0d0cef4d67f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-form&quot;)/div[@class=&quot;modal-input-holder&quot;]/div[@class=&quot;modal-input-layout-item calendar&quot;]/div[@class=&quot;react-datepicker-wrapper&quot;]/div[@class=&quot;react-datepicker__input-container&quot;]/div[@class=&quot;modal-input-field-holder date-input-holder&quot;]/input[@class=&quot;modal-input input-text with-border date-input input-date-cursor&quot;]</value>
      <webElementGuid>fde05fbe-2ed2-4c03-9bf2-b88201277d9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='projectedEtaDate']</value>
      <webElementGuid>e5e1bd63-e5bf-4e12-90d2-4e6d9aafea52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my-form']/div[5]/div/div/div/div/input</value>
      <webElementGuid>33977c5b-a964-42b3-b1d1-5a58ba9d64d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/input</value>
      <webElementGuid>e080b01e-c51e-415d-acc6-cee8aef61441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'dd-mm-yyyy' and @name = 'projectedEtaDate']</value>
      <webElementGuid>aa3c1372-b355-4468-bf17-72e32b3acd3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
