<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__packaging_declaration</name>
   <tag></tag>
   <elementGuidId>8cc82cff-5cfe-4b66-ba0f-13650e7a1ca0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='ad_file'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee30ec35-696a-44cc-a1c8-f9033c1a81bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>cdd69456-0afe-4723-adbe-1317f06912cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ad_file</value>
      <webElementGuid>22dd750e-8701-4312-8ea4-1bc20e60d062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ad_file</value>
      <webElementGuid>938ce982-a6d4-44a7-a8a4-4728a7f60f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.doc,.docx,.mpp,.mppx,.pdf,.ppsx,.ppt,.pptx,.vsd,.vsdx,.xls,.xlsx</value>
      <webElementGuid>fe024b7c-6329-4255-b258-aef60838b0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>browse-input</value>
      <webElementGuid>da252010-fbb8-43e0-9379-6380b217456d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-wrapper container&quot;]/div[@class=&quot;content-section main-wrapper bo-additional-detail&quot;]/div[@class=&quot;main-wrapper&quot;]/div[@class=&quot;booking-attachment-wrapper&quot;]/div[@class=&quot;attachments-wrapper&quot;]/div[@class=&quot;card details-box custom&quot;]/div[@class=&quot;card-detail-col&quot;]/div[@class=&quot;attachment-items-holder&quot;]/div[@class=&quot;modal-input-holder upload-file-btn&quot;]/div[@class=&quot;modal-input-layout-item&quot;]/div[@class=&quot;browse-btn-wrapper&quot;]/input[@id=&quot;ad_file&quot;]</value>
      <webElementGuid>881429b7-9d73-466e-8e28-502d66183ed2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='ad_file'])[7]</value>
      <webElementGuid>714db1de-67e2-4779-8e6f-27b3454d64ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/div/div/div[2]/div[7]/div[2]/div/div/div/div/input</value>
      <webElementGuid>3750f8bb-7a0e-4318-9cf0-600079752ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/div/div/input</value>
      <webElementGuid>013f2c4e-6afe-4a3b-a901-a573e1b0420b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'ad_file' and @name = 'ad_file']</value>
      <webElementGuid>50f6ca5c-4050-47c4-a074-88f6594b879c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
