<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__hazardous_certificate</name>
   <tag></tag>
   <elementGuidId>cfccf039-f7fa-42d7-aa0d-1b2d96d958cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='ad_file'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80fce2ad-b380-4663-b418-8c901ce35d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>28a8d6f1-ed97-4391-bbcc-1121a7446dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ad_file</value>
      <webElementGuid>b8fccc06-69f1-4c87-ada3-804c541682c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ad_file</value>
      <webElementGuid>6703b1a4-4f34-4210-8ed0-4626bbc9b9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.doc,.docx,.mpp,.mppx,.pdf,.ppsx,.ppt,.pptx,.vsd,.vsdx,.xls,.xlsx</value>
      <webElementGuid>2e0b10f6-cb40-48dc-b7b4-f436441542e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>browse-input</value>
      <webElementGuid>eaf2fccf-34ef-4153-919b-d44accc09cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-wrapper container&quot;]/div[@class=&quot;content-section main-wrapper bo-additional-detail&quot;]/div[@class=&quot;main-wrapper&quot;]/div[@class=&quot;booking-attachment-wrapper&quot;]/div[@class=&quot;attachments-wrapper&quot;]/div[@class=&quot;card details-box custom&quot;]/div[@class=&quot;card-detail-col&quot;]/div[@class=&quot;attachment-items-holder&quot;]/div[@class=&quot;modal-input-holder upload-file-btn&quot;]/div[@class=&quot;modal-input-layout-item&quot;]/div[@class=&quot;browse-btn-wrapper&quot;]/input[@id=&quot;ad_file&quot;]</value>
      <webElementGuid>7da4e9ad-5ed7-498e-abb5-b6353ea79b63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='ad_file'])[4]</value>
      <webElementGuid>5fba00b9-2058-4d9f-a049-245da7132037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/div/div/div[2]/div[4]/div[2]/div/div/div/div/input</value>
      <webElementGuid>d8ad482f-b446-4039-8537-960aec2da740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div/input</value>
      <webElementGuid>1a5de3de-1900-438c-9a09-93c29ca70edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'ad_file' and @name = 'ad_file']</value>
      <webElementGuid>7a61c38c-909e-47d9-8c0d-da4ce2070c2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
