<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__originCartageCompany</name>
   <tag></tag>
   <elementGuidId>c5bb811e-f678-4acd-8873-b6629e110c72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#originCartageCompany</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='originCartageCompany']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80b06d87-6777-4f42-8706-50741fe2633f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Origin Cartage Company</value>
      <webElementGuid>0c49479f-53f4-48d8-9b82-e19d6a1be2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa5f9d13-8f36-4e6a-8f9f-d4bca7cc13e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text</value>
      <webElementGuid>92ef86d7-36d8-48c1-b336-b3557978cce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>originCartageCompany</value>
      <webElementGuid>779fe08a-e728-4b93-a208-b4aefeb92004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>originCartageCompany</value>
      <webElementGuid>c058379e-0622-408e-941d-e43d304f0777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>b05ea6e0-24dd-4f80-8258-4c10e53b0afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;originCartageCompany&quot;)</value>
      <webElementGuid>b2d535df-36fb-4977-86b0-65fc2fb39585</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='originCartageCompany']</value>
      <webElementGuid>6f190342-0116-4f91-bd54-74c8b014934e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='name_div']/div/input)[4]</value>
      <webElementGuid>bb68e161-dad0-4f5d-8496-bd46b58d6260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>2ff6721f-c874-4c90-89a3-b7c00b8b690b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Origin Cartage Company' and @type = 'text' and @id = 'originCartageCompany' and @name = 'originCartageCompany']</value>
      <webElementGuid>4f76e224-1bb4-4d5b-ab66-b524cf42ee4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
