<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__lading_bill</name>
   <tag></tag>
   <elementGuidId>b39703fe-1ca0-4977-b462-7a7becfe3166</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='ad_file'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5236b8e-c553-4e19-901b-fa782d9d7e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>3eed7777-1c72-42d4-b26c-58c5e67b8b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ad_file</value>
      <webElementGuid>019c28f0-6a04-4ad1-8a4c-0edb417e56e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ad_file</value>
      <webElementGuid>4c8c785f-7e34-44e7-9026-9c3cc7393ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.doc,.docx,.mpp,.mppx,.pdf,.ppsx,.ppt,.pptx,.vsd,.vsdx,.xls,.xlsx</value>
      <webElementGuid>f38097fe-76cd-42e3-b514-df2ffa9c72d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>browse-input</value>
      <webElementGuid>f00f8ba5-72e3-47b2-919b-7ca10733a1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-wrapper container&quot;]/div[@class=&quot;content-section main-wrapper bo-additional-detail&quot;]/div[@class=&quot;main-wrapper&quot;]/div[@class=&quot;booking-attachment-wrapper&quot;]/div[@class=&quot;attachments-wrapper&quot;]/div[@class=&quot;card details-box custom&quot;]/div[@class=&quot;card-detail-col&quot;]/div[@class=&quot;attachment-items-holder&quot;]/div[@class=&quot;modal-input-holder upload-file-btn&quot;]/div[@class=&quot;modal-input-layout-item&quot;]/div[@class=&quot;browse-btn-wrapper&quot;]/input[@id=&quot;ad_file&quot;]</value>
      <webElementGuid>90c5d4f5-dbe7-48e7-aede-894919e79d98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='ad_file'])[5]</value>
      <webElementGuid>875d8079-4523-4584-a961-a1b8bdcd51d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/div/div/div[2]/div[5]/div[2]/div/div/div/div/input</value>
      <webElementGuid>bf19c6a3-23e1-4379-a613-eb04e10ba055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div/input</value>
      <webElementGuid>2c1b1159-2c11-4709-bb79-0217ccbaefaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'ad_file' and @name = 'ad_file']</value>
      <webElementGuid>f46818c6-db97-41a4-9704-41a1f8729532</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
