<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__costSellAmount</name>
   <tag></tag>
   <elementGuidId>1769e75c-6abb-498a-8316-b0df49503a4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#costSellAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='costSellAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58919c77-4b96-4a9d-9dcb-852827a4acb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Cost</value>
      <webElementGuid>6c05f337-35b7-4147-870d-6e355d1a33f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>091a62b4-0c84-421c-8653-4eb768a21cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>0c681c6f-3874-421b-bb3e-db5f8b2087ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ade592ed-d1fb-4483-a48d-ffb3bfc1bfac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>costSellAmount</value>
      <webElementGuid>e26f2b1a-3ec6-4a9e-9e53-4705dfbbd3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>costSellAmount</value>
      <webElementGuid>12ad03f8-661c-4240-8651-bc46ff7c31ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text</value>
      <webElementGuid>15adfc58-419d-4be1-b3d7-e5546069c43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;costSellAmount&quot;)</value>
      <webElementGuid>b423d8fd-de34-4f28-b1f0-72f146338c8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='costSellAmount']</value>
      <webElementGuid>4e3b196a-0a83-444b-9000-abd868b03b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my-form']/div[3]/div/div/div/input</value>
      <webElementGuid>8b486ef1-9dd4-4568-8bcc-8fd6053a1702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>01c7f489-082a-4d55-9e86-b9ed6c81ea2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Cost' and @type = 'number' and @id = 'costSellAmount' and @name = 'costSellAmount']</value>
      <webElementGuid>75c9a03c-561d-4c17-98aa-37bc04295607</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
