<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(9699 O, , Conner Circle, Water_b99838</name>
   <tag></tag>
   <elementGuidId>860f7939-5d0e-4b80-b1fa-cf6afeff41a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmedQty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmedQty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3c3479c-26e4-4844-8ce1-79b294614d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27845da9-bdb3-404c-92b0-ace62daa346b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-input input-text input-qty</value>
      <webElementGuid>2a3587f6-3d28-4de9-9e73-14db56bcf424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmedQty</value>
      <webElementGuid>1ad64173-1adf-4db4-a25b-66a0ff09bda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmedQty</value>
      <webElementGuid>88a65d99-11bc-4b73-af3d-c54afbdc690b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmedQty&quot;)</value>
      <webElementGuid>89dba3c9-b7d3-487c-8b03-dadafc490367</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmedQty']</value>
      <webElementGuid>20ed1369-a034-47b3-b882-ca794486d964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my-form']/table/tbody/tr[2]/td[6]/div/input</value>
      <webElementGuid>7c9af0c5-e8a9-491e-afda-7a30d09c123e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/input</value>
      <webElementGuid>bc22a987-b8f6-4d93-ab08-776eb5e197f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'confirmedQty' and @name = 'confirmedQty']</value>
      <webElementGuid>59e69751-bae2-4287-9059-d1dafaf33934</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
