<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__costBuyAmount</name>
   <tag></tag>
   <elementGuidId>45d03441-fe90-4e5a-a40b-93ee1866a0f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#costBuyAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='costBuyAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85797432-8f74-453d-a5f8-19cc05b77c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Cost</value>
      <webElementGuid>3a3a62ef-be9b-4c23-906c-c0c752f1c8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ef3d84d6-c7d9-4e7a-8bfa-16be4e9b29a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e3eb3145-854d-49d0-87e0-197583ab07c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>7945bec4-5d8f-44f1-93d8-6a7daedd27fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>costBuyAmount</value>
      <webElementGuid>d52bad70-7b72-4fa1-aa4b-1dd6b862a6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>costBuyAmount</value>
      <webElementGuid>606c84ff-72c8-4867-8ca9-062a425c8d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text 
                                                </value>
      <webElementGuid>8276d569-fd87-476d-ad95-da8017e2e5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;costBuyAmount&quot;)</value>
      <webElementGuid>1ad67067-cc1e-4c25-bb59-8d18dbf939d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='costBuyAmount']</value>
      <webElementGuid>cb33b471-1a76-408a-bae3-5008c65f0a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my-form']/div[2]/div/div/div/input</value>
      <webElementGuid>a31423ee-66e8-48bb-a5e7-f53594a147a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>62d64550-f242-4db5-b6b4-e5a9dd413b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Cost' and @type = 'number' and @id = 'costBuyAmount' and @name = 'costBuyAmount']</value>
      <webElementGuid>3f1f463d-6a6e-4490-8cbd-5b7100a56881</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
