<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select Packingdropdown</name>
   <tag></tag>
   <elementGuidId>7041119b-3709-43c7-a27d-35f202a8b063</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>daaadb25-0c60-47e5-a604-136219b2b60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d25d0ac0-1402-4c92-ac4d-bfb86e87da0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-btn app-btn select-modal</value>
      <webElementGuid>732bfd7a-2af0-4187-b4c8-657810cd00f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Packingdropdown</value>
      <webElementGuid>4818eb12-db7d-4d44-aeaa-420eb45b3456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic-details&quot;)/div[@class=&quot;modal-input-holder&quot;]/div[@class=&quot;modal-input-field-holder grey-option-box modal-input-layout-item&quot;]/div[@class=&quot;dropdown-wrap menu-down modal-dropdown&quot;]/button[@class=&quot;menu-btn app-btn select-modal&quot;]</value>
      <webElementGuid>2e9a3238-cb64-4a81-a27f-814f6f5e8532</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>4e1d4daa-b908-4542-8bb3-b7f914b7d129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic-details']/div[5]/div/div/button</value>
      <webElementGuid>5bffa135-e8a7-49b5-9d3d-b52ddbffc024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/following::button[1]</value>
      <webElementGuid>78857488-1203-4399-81f9-ebf7edc46c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double Pallet'])[1]/preceding::button[1]</value>
      <webElementGuid>019c1d35-11eb-431d-a336-705bb556fa41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/button</value>
      <webElementGuid>1fec6bf5-4f51-48a1-b72c-22078578ba4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Select Packingdropdown' or . = 'Select Packingdropdown')]</value>
      <webElementGuid>c67eb78e-1795-4468-8149-0442df6b97d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
