<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__bookingRefNum</name>
   <tag></tag>
   <elementGuidId>2937defd-ce0c-46a4-bdc5-003ef0375030</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bookingRefNum</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bookingRefNum']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81f12124-db91-4645-a55a-476e2ba26779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Booking Reference No.</value>
      <webElementGuid>3429b8f9-cb5f-4aeb-8631-b4e245a6c68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a335a3a-eecd-451b-b6ba-6c35f6956e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text</value>
      <webElementGuid>fddd4dc2-82df-4b46-9315-49a22958a26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bookingRefNum</value>
      <webElementGuid>d1b2d8b0-0481-47a3-b135-509485499f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bookingRefNum</value>
      <webElementGuid>326f227c-4e69-4256-b8cb-1ae2ca5fc9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>b3a87207-fc4d-4426-901b-696d1b46be5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bookingRefNum&quot;)</value>
      <webElementGuid>d3722705-4787-427e-a459-6f1fccdebf25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bookingRefNum']</value>
      <webElementGuid>0649ad31-791c-4d85-bc20-3087f8770395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name_div']/div/input</value>
      <webElementGuid>e8f1c729-a58f-44d3-b370-b7ce82bf37db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>87d8d218-937c-4f21-99e5-ec314824c76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Booking Reference No.' and @type = 'text' and @id = 'bookingRefNum' and @name = 'bookingRefNum']</value>
      <webElementGuid>7d89cfbd-b0e8-4e34-ac41-bd6654c6af87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
