<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__containerNumber</name>
   <tag></tag>
   <elementGuidId>73b478c7-a53e-43b9-908d-ea0046522964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#containerNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='containerNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4123bd30-b2d0-4384-9058-790838670c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Container Number</value>
      <webElementGuid>fa5be4ba-0d4c-4b12-9c97-20a2a44b430f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c50e8f32-4bdc-4c0a-9dc5-9f948b74cb25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text</value>
      <webElementGuid>d1108eca-106c-420a-bb93-087da0bc7976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>containerNumber</value>
      <webElementGuid>b1a2dbe9-8848-4e13-a3d7-121067074e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>containerNumber</value>
      <webElementGuid>06e63b56-5e10-4dcf-bb73-a8ba09c6c379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;containerNumber&quot;)</value>
      <webElementGuid>4c176ff5-69b0-4523-8c20-35c51c3c88dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='containerNumber']</value>
      <webElementGuid>63285277-6eac-4c68-b784-a0d2eb5cbed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic-details']/div[4]/div/input</value>
      <webElementGuid>3e898756-b807-4d4e-91eb-ad6c597329cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>547d1a25-f7e7-4b66-aa13-bb172386d468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Container Number' and @type = 'text' and @id = 'containerNumber' and @name = 'containerNumber']</value>
      <webElementGuid>de909fe7-83e9-41e5-a97f-8bbff26e89e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
