<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__sealNumber</name>
   <tag></tag>
   <elementGuidId>28815471-eb77-4888-986e-93d0ef4b8f68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sealNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sealNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ee5bfb1-94c9-4c76-8877-d43b17d93549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Seal No</value>
      <webElementGuid>303b97de-d948-48cf-bf44-6b7aa3de8cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94f61d52-f6be-4fa0-8b54-b7dc83c73554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text</value>
      <webElementGuid>1f36b0bc-6dd1-4f6a-a2e8-687557996f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sealNumber</value>
      <webElementGuid>fdc2374a-5290-489e-a8c8-1e446ec136a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sealNumber</value>
      <webElementGuid>717d2b1d-05c2-4a18-9cb0-aea17db6d7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sealNumber&quot;)</value>
      <webElementGuid>78d63324-dbbb-4c83-bcc2-7d62d6aefd7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sealNumber']</value>
      <webElementGuid>2f74ccee-3bd2-4282-9f8e-28f3d2e4eca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic-details']/div[6]/div/input</value>
      <webElementGuid>a4ab7933-f323-44c0-92c3-55533ad123c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>8d164f32-fbe7-498a-8813-4b9f2b4350a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Seal No' and @type = 'text' and @id = 'sealNumber' and @name = 'sealNumber']</value>
      <webElementGuid>ee17fef7-2bec-458f-bffd-43837159c9b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
