<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sary(IRSRY)</name>
   <tag></tag>
   <elementGuidId>1112f7c2-c945-4ba1-bbc7-b5ba5a2befce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-5-option-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Sary(IRSRY)' or . = 'Sary(IRSRY)')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>96d7ca30-40a8-4c7f-994f-b883280522df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-a4wmji-option</value>
      <webElementGuid>8b68504c-136a-4359-b18e-afdfbf8baaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f6476705-e74a-45f5-8364-723ff9279f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-5-option-2</value>
      <webElementGuid>28e5c03b-841b-4c02-aa1e-f421a0740cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7afa2c9a-1c84-4fba-acbb-4224d6a24e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sary(IRSRY)</value>
      <webElementGuid>94e44d33-4e67-41c9-9a95-63a5e7d0cd5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-5-option-2&quot;)</value>
      <webElementGuid>aacdfc2d-4edf-4edc-8a68-ec11b9b11c3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-5-option-2']</value>
      <webElementGuid>dd2b2787-8dbe-4327-97da-ad2759e0d8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-5-listbox']/div/div[3]</value>
      <webElementGuid>e04357b5-9e58-4874-9a48-02ff56b30226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decorah(USDEH)'])[1]/following::div[1]</value>
      <webElementGuid>e56eb8ea-9415-4ba8-bcfc-d121e990e399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soddu(ETSXU)'])[1]/following::div[2]</value>
      <webElementGuid>a121b93f-d3e0-4811-91f2-52e904c11814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akyab Sittwe(MMAKY)'])[1]/preceding::div[1]</value>
      <webElementGuid>00b25e39-e444-4962-8623-002e7a12e256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brisbane(AUBNE)'])[1]/preceding::div[2]</value>
      <webElementGuid>aae6f65d-4155-4a1f-aeb3-11f3064fa23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sary(IRSRY)']/parent::*</value>
      <webElementGuid>0f776fe0-37b2-459d-9fd3-6957d05488f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div[3]</value>
      <webElementGuid>4950d15c-1ce0-4e3b-a2c7-b48afa3b250a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-5-option-2' and (text() = 'Sary(IRSRY)' or . = 'Sary(IRSRY)')]</value>
      <webElementGuid>e1dfecde-78c5-49a3-bd5d-3a78454621b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
