<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Goods Ready Date_goodsReadyDate</name>
   <tag></tag>
   <elementGuidId>fb2f59fc-1097-47fc-991c-e199e2a44f13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;goodsReadyDate&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='goodsReadyDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9002d60-9647-49c7-9dc8-be8de2399d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text with-border date-input input-date-cursor</value>
      <webElementGuid>f0966d2e-8142-4dfd-8202-f9d634c34023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4341ad29-9405-4df3-b709-281fb6eaa4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>cc244a60-9986-4195-93b6-e7af075883ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>goodsReadyDate</value>
      <webElementGuid>a1a9c1a5-803b-4510-8b95-7f59c5ec5c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-form&quot;)/div[@class=&quot;modal-input-holder&quot;]/div[@class=&quot;modal-input-layout-item calendar&quot;]/div[@class=&quot;react-datepicker-wrapper&quot;]/div[@class=&quot;react-datepicker__input-container&quot;]/div[@class=&quot;modal-input-field-holder date-input-holder&quot;]/input[@class=&quot;modal-input input-text with-border date-input input-date-cursor&quot;]</value>
      <webElementGuid>8154be3c-d51f-4f20-ac23-c8d834685c6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='goodsReadyDate']</value>
      <webElementGuid>9d2c1301-d705-408a-a053-19afe143ac91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my-form']/div[4]/div/div/div/div/input</value>
      <webElementGuid>abad503f-fe64-4c5f-bedd-222703d19151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>63e22e2b-ff08-46ce-86c9-8b181d1863a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'dd-mm-yyyy' and @name = 'goodsReadyDate']</value>
      <webElementGuid>8d7b7693-ddaa-4e01-bb91-ecdfb5e24d26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
