<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PO Number_poNumber</name>
   <tag></tag>
   <elementGuidId>989a5567-694f-42e6-8829-c436f33b1e31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#poNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='poNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9752f75d-cf25-48bd-9668-e36da06917ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter PO Number</value>
      <webElementGuid>057eb6fa-dc3a-4bd0-9c3d-17282f6e0926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea025f81-1bad-4f70-9d95-fe6266d8e438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text</value>
      <webElementGuid>2a4e855d-2a29-445e-abac-26f263b1e487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>poNumber</value>
      <webElementGuid>b71e3c0a-1103-49ca-b419-e74a35696623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>poNumber</value>
      <webElementGuid>2938be98-d085-42b7-acc7-60e42defa753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;poNumber&quot;)</value>
      <webElementGuid>113e0ea2-c1c7-4387-bd2f-d4080233cae9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='poNumber']</value>
      <webElementGuid>3e4602bc-19d6-45aa-8377-165310f6bd5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my-form']/div/div/input</value>
      <webElementGuid>6dea2139-6f4d-46c5-a0e8-79d7f28e51aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b68f0fdc-dd0e-452e-b195-9aa29e3f9936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter PO Number' and @type = 'text' and @id = 'poNumber' and @name = 'poNumber']</value>
      <webElementGuid>93704426-19a5-4f9b-8629-bc1247106c1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
