<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_9699 OConner Circle, Waters Ports, Hunt_dd8b07</name>
   <tag></tag>
   <elementGuidId>0d65b641-e16a-41b9-ab70-a66704ca9bbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-6-option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-6-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>91fac34f-f1ba-48ec-9456-5bc77cd3f790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-select__option react-select__option--is-focused css-7141g7-option</value>
      <webElementGuid>f424cc62-5e5a-44a9-8956-c735c5fadb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>41dd2902-f23c-4dc7-9a8a-974a0322a6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-6-option-0</value>
      <webElementGuid>64d21b4c-07e5-4099-8d54-96ea5afa0966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>426389b6-ade9-4fb9-9247-2b55167fd061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9699 O'Conner Circle, Waters Ports, Huntington, Kerlukestad, Laurettaport, 4215</value>
      <webElementGuid>3dd6b333-0495-4616-ba31-8c46f60c4a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-6-option-0&quot;)</value>
      <webElementGuid>92023700-a1fc-4fec-ac33-8a40ad861876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-6-option-0']</value>
      <webElementGuid>41c946aa-7442-43cd-bbae-648b6318acad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-6-listbox']/div/div</value>
      <webElementGuid>ec6012dc-e695-4353-8f9b-dd5260c695fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Destination Address'])[1]/following::div[5]</value>
      <webElementGuid>d4e614c1-b9bc-4eb4-910c-29a989a6036d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/following::div[10]</value>
      <webElementGuid>7ac7a2b4-0f6f-4e3e-bf65-fdd0b00e43b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[14]/preceding::div[1]</value>
      <webElementGuid>ef3354c6-685b-4749-ab34-22485a1281dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div</value>
      <webElementGuid>76983fd0-4159-4299-9079-8ff183841f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-6-option-0' and (text() = concat(&quot;9699 O&quot; , &quot;'&quot; , &quot;Conner Circle, Waters Ports, Huntington, Kerlukestad, Laurettaport, 4215&quot;) or . = concat(&quot;9699 O&quot; , &quot;'&quot; , &quot;Conner Circle, Waters Ports, Huntington, Kerlukestad, Laurettaport, 4215&quot;))]</value>
      <webElementGuid>996a7479-3469-4b00-8f43-b6545469801d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
