<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PO Number_poNumber</name>
   <tag></tag>
   <elementGuidId>2649ea63-575c-4a59-a531-f75478d2c597</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#poNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='poNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35c10d13-3b0f-4f69-b0d3-bd288c7150ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter PO Number</value>
      <webElementGuid>7354bf35-767d-4179-b5e9-f916e9eb09c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>26b30db2-2848-4742-ae36-1cf9f845b0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input input-text</value>
      <webElementGuid>ef57cc98-c99e-45b3-ba54-a19429ac657e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>poNumber</value>
      <webElementGuid>b55389f1-3d01-4806-b1d1-149fa2b3a207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>poNumber</value>
      <webElementGuid>52b8cc4f-d15c-481a-8007-a18ebae24722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;poNumber&quot;)</value>
      <webElementGuid>6f546a4b-963f-4282-8f99-d584ff35bb22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='poNumber']</value>
      <webElementGuid>a91c667f-c6c4-4849-8dda-302cc2213c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my-form']/div/div/input</value>
      <webElementGuid>0a03185c-c1e3-4a3b-9856-4f81d3f8d0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>4445bce7-f044-4611-a7e1-8696ce448912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter PO Number' and @type = 'text' and @id = 'poNumber' and @name = 'poNumber']</value>
      <webElementGuid>bf4afff7-b1b6-47f2-954d-52503f83508b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
